---
simulation_env: "bedroom"
rviz2: true
human_1: 
 velocity: 2
 traj: "test_motion.bin"
human_2: 
 velocity: 1
 traj: "test_motion.bin"
human_3: 
 velocity: 3
 traj: "test_motion.bin"
lidar_1:
 x: 3
 y: -3
 z: 0.6
 rx: 0
 ry: 0
 rz: 0
 channels: 32
 rate: 20
lidar_2:
 x: 2
 y: 0
 z: 0.7
 rx: 0
 ry: 0
 rz: 0
 channels: 16
 rate: 20
