---
simulation_env: "bedroom"
rviz2: true
static_lidar: true
human_1: 
 velocity: 1.0
 pace: 1.0
 traj: "test_motion.bin"
 anim_t: 2.0
 anim_f: 'showing.dae'
lidar_1:
 x: 2.5
 y: -2.5
 z: 1.2
 rx: 0
 ry: 0
 rz: 0
 channels: 64
 rate: 20
